name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install rustdoc
        run: rustup component add rustdoc

      - name: Build documentation
        run: |
          cargo doc --no-deps --document-private-items
          echo '<meta http-equiv="refresh" content="0; url=universal_lsp/index.html">' > target/doc/index.html

      - name: Apply custom theme
        run: |
          cp docs/theme/universal-lsp.css target/doc/
          find target/doc -name "*.html" -type f -exec sed -i 's|<head>|<head><link rel="stylesheet" type="text/css" href="/universal-lsp.css">|' {} \;

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/doc'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
